spring.application.name=Finsight-backend

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.security=debug

spring.datasource.url=jdbc:postgresql://localhost:5432/finsight
spring.datasource.username=postgres
spring.datasource.password=project

